version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "Cloud-Resume-SAM-Stack"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-vvx44yeecdu7"
s3_prefix = "Cloud-Resume-SAM-Stack"
region = "eu-central-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
disable_rollback = true
image_repositories = []
